// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ifleyyqxxpdnmmhautio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlmbGV5eXF4eHBkbm1taGF1dGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxMDU3ODksImV4cCI6MjA3NDY4MTc4OX0.FP6UscD6VT9xsBd5DoyXvc7a1iLKprrfhejsSaXU8PA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});